Blog Application/mysite/blog/urls.py
from django.urls import path
from . import views

# Define application namespace allowing to organize URLs by application adn use the name when referring to them
app_name = 'blog'

urlpatterns = [
    # as_view() method is used because path expect a callable function, not a class
    path('', views.PostListView.as_view(), name='post-list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post-list-by-tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', 
         views.post_detail, 
         name='post_detail'), # Angle brackets is used to capture the values from the URL
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

Blog Application/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Namespaces (blog:post_list) must be unique across the entire project
    path('blog/', include('blog.urls', namespace='blog'))
]

Blog Application/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return (
            # The get_queryset() return the QuerySet that will be executed
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        )
# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(  # Implies an index by default
        max_length=250,
        # Unique for date is not enforced at the database level, so no database migration is required
        unique_for_date='publish',
        )
    # Defines a many-to-one relationship between Users and Posts
    author = models.ForeignKey( # Implies an index by default
        settings.AUTH_USER_MODEL, # Points to auth.User by default
        on_delete=models.CASCADE,
        null=True,
        related_name='blog_posts', # specify the name of the reverse relationship, e.g. user.blog_posts
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now) # Has an index specifies in the Meta class
    # auto_now_add saves the date automatically when creating an object (tracks creation time)
    created = models.DateTimeField(auto_now_add=True)
    # auto_now will automatically update the date when saving an object (tracks last modification time)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT,
    )
    # If you declare any managers for the model but want to keep the objects manager, you have to add it explicity
    objects = models.Manager() # The default manager
    published = PublishedManager() # The custom manager
    tags = TaggableManager()

    # This class defines metadata for the model
    class Meta:
        # This order takes effect unless a specific order is indicated in the query
        ordering = ['-publish'] # We can indicate descending order by using a hyphen before the field name
        indexes = [
            models.Index(fields=['-publish']), # The index will be generated in descending order
        ]

    # Django uses this method to return a string with the human-readable representation of the object
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # Builds the URL dynamically using the URL name defined in the URL patterns
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
                ]
        )
    
class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    name  = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # Allows comments to be manually deactivated using the administration site
    active = models.BooleanField(default=True) # Comments are active by default

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return f'Comments by { self.name } on {self.post}'

Blog Application/mysite/blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

class CommentForm(forms.ModelForm):
    class Meta:
        # Django will introspect the model and build the corresponding form dinamically
        model = Comment
        # Defines which fields are included in the form (the opposite is exclude)
        fields = ['name', 'email', 'body']

Blog Application/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView
from django.views.decorators.http import require_POST

from taggit.models import Tag

from .forms import EmailPostForm, CommentForm
from .models  import Post

class PostListView(ListView): #ListView allows to list any type of object
    """Alternative post list view"""
    # Defines a custom QuerySet, it is possible to specified model = Post
    # queryset = Post.published.all()
    # We use the context variable posts for the query results (default variable is object_list)
    context_object_name = 'posts'
    # We define pagination os results returnig three objects per page
    paginate_by = 3
    # Defines custom template to render the page (default template is blog/post_list.html)
    template_name = 'blog/post/list.html'

    def get_queryset(self):
        tag_slug = self.kwargs.get("tag_slug")
        if tag_slug is not None:
            return Post.published.filter(tags__slug=tag_slug)
        return Post.published.all()
    
    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        tag_slug = self.kwargs.get("tag_slug")
        if tag_slug is not None:
            context["tag"] = Tag.objects.filter(slug=tag_slug).first()
            return context
        return context

def post_detail(request:HttpRequest, year:int, month:int, day:int, post:str) -> HttpResponse:
    # retriever the object that matches the given parameters or an HTTP404 exception
    post = get_object_or_404(Post, 
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return render(
        request,
        template_name='blog/post/detail.html',
        context={
            'post': post,
            'comments': comments,
            'form': form,},
    )

# Why not a class-based view form instead function-based one
def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )
    # Used to display a success message when the form is successufully submitted
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(  # Build a complete URL, i.e. with Http schema and hostname
                post.get_absolute_url(), # Retrives the absolute path of the post
            )
            subject = (
                f'{ cd["name"] } <{ cd["email"] }>'
                f' recommends you read { post.title }'
            )
            message = (
                f'Read { post.title } at { post_url }\n\n'
                f'{ cd["name"] }\'s comments: PUT COMMENTS IN HERE'
            )
            # From_email=None the default value will be the DEFAULT_FROM_MAIL
            if send_mail(subject, message, from_email=None, recipient_list=[cd['to']]) == 1:
                sent = True

    else:
        form = EmailPostForm()

    return render(
        request,
        template_name='blog/post/share.html',
        context={
            'post': post,
            'form': form,
            'sent': sent,
        }
    )

# Django will throw an HTTP 405 error if you try to access the view with any other HTTP method
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )
    comment = None

    form = CommentForm(data=request.POST)

    if form.is_valid():
        # Commit=false the model instance is created but not saved to the database
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment,
        }
    )

Blog Application/mysite/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include 'blog/post/includes/comment_form.html' %}
    {% endif %}
{% endblock %}

Blog Application/mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>
    {% with comments.count as total_comments %}
        {% comment %} pluralize returns a "s" letter if the value is different from 1 {% endcomment %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>There are no comments.</p>
    {% endfor %}
    {% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

Blog Application/mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </h2>
        {% comment %} join function concatenates a list of items into one string {% endcomment %}
        <p class="tags">Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

Blog Application/mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {% comment %} Tells django to render the form fields using HTML paragraph elements {% endcomment %}
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}